language: c
os:
  - osx
install:
  - wget https://dl.dropboxusercontent.com/u/12595498/pspsdk.tar.gz
  - tar -vzxf pspsdk.tar.gz
  #- export PSPSDK="$PSPDEV/psp/sdk"
  #- export PATH="$PATH:$PSPDEV/bin:$PSPSDK/bin"
#echo yes | $PSPDEV $PSPSDK $PATH > log.txt
before_script:
	#- export PSPDEV="$TRAVIS_BUILD_DIR/pspsdk"
	#- export PSPDEV=`pwd`/pspsdk
echo yes | `pwd` > log.txt
echo yes | `ls` > log2.txt
script: make
